version: '3.7'
services:
  web:
    build: .
    working_dir: /code
    volumes:
      - .:/code
    ports:
      - "4000:4000"
    command: >
      mix do local.hex --force,
             local.rebar --force,
             deps.get,
             compile,
             phx.server

volumes:
  code:
